### ISSUE TITLE
AUR .tar.gz link is not found

### ISSUE THREAD

**Issue by a-andreyev** [stroobantstom/duckdns#1]
Hello! Thank your great project!
I know it is working, but apropriate arch linux package is missing at your server right now.
Could you check it or should we just update the PKGBUILD to support your github repo?
(Propably just update the link to `https://github.com/stroobantstom/duckdns/archive/master.zip`, apropiate md5sum and change from `cd duckdns` to `duckdns-master`

**Comment by T00mm** [comment]
Hi, it seems I've put some mail settings wrong and I just noticed these issues. I'm terribly sorry for the two years wait (not a big github user ;-) ). I've also seen someone has already updated the PKGBUILD on the AUR repositories so I will close this issue. I will also start checking Github more ;-)
